// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import models "github.com/pisatoo/pst-master/models"

// LxcRepository is an autogenerated mock type for the LxcRepository type
type LxcRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: l
func (_m *LxcRepository) Create(l models.LXC) models.LXC {
	ret := _m.Called(l)

	var r0 models.LXC
	if rf, ok := ret.Get(0).(func(models.LXC) models.LXC); ok {
		r0 = rf(l)
	} else {
		r0 = ret.Get(0).(models.LXC)
	}

	return r0
}

// Delete provides a mock function with given fields: id
func (_m *LxcRepository) Delete(id int) bool {
	ret := _m.Called(id)

	var r0 bool
	if rf, ok := ret.Get(0).(func(int) bool); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Lxc provides a mock function with given fields: id
func (_m *LxcRepository) Lxc(id int) models.LXC {
	ret := _m.Called(id)

	var r0 models.LXC
	if rf, ok := ret.Get(0).(func(int) models.LXC); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(models.LXC)
	}

	return r0
}

// Lxcs provides a mock function with given fields:
func (_m *LxcRepository) Lxcs() []models.LXC {
	ret := _m.Called()

	var r0 []models.LXC
	if rf, ok := ret.Get(0).(func() []models.LXC); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.LXC)
		}
	}

	return r0
}

// Update provides a mock function with given fields: id, l
func (_m *LxcRepository) Update(id int, l models.LXC) models.LXC {
	ret := _m.Called(id, l)

	var r0 models.LXC
	if rf, ok := ret.Get(0).(func(int, models.LXC) models.LXC); ok {
		r0 = rf(id, l)
	} else {
		r0 = ret.Get(0).(models.LXC)
	}

	return r0
}
