// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import models "github.com/pisatoo/pst-master/models"

// LxdRepository is an autogenerated mock type for the LxdRepository type
type LxdRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: l
func (_m *LxdRepository) Create(l models.LXD) (models.LXD, error) {
	ret := _m.Called(l)

	var r0 models.LXD
	if rf, ok := ret.Get(0).(func(models.LXD) models.LXD); ok {
		r0 = rf(l)
	} else {
		r0 = ret.Get(0).(models.LXD)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(models.LXD) error); ok {
		r1 = rf(l)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: id
func (_m *LxdRepository) Delete(id int) (bool, error) {
	ret := _m.Called(id)

	var r0 bool
	if rf, ok := ret.Get(0).(func(int) bool); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Lxd provides a mock function with given fields: id
func (_m *LxdRepository) Lxd(id int) (models.LXD, error) {
	ret := _m.Called(id)

	var r0 models.LXD
	if rf, ok := ret.Get(0).(func(int) models.LXD); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(models.LXD)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Lxds provides a mock function with given fields:
func (_m *LxdRepository) Lxds() ([]models.LXD, error) {
	ret := _m.Called()

	var r0 []models.LXD
	if rf, ok := ret.Get(0).(func() []models.LXD); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.LXD)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: id, l
func (_m *LxdRepository) Update(id int, l models.LXD) (models.LXD, error) {
	ret := _m.Called(id, l)

	var r0 models.LXD
	if rf, ok := ret.Get(0).(func(int, models.LXD) models.LXD); ok {
		r0 = rf(id, l)
	} else {
		r0 = ret.Get(0).(models.LXD)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, models.LXD) error); ok {
		r1 = rf(id, l)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
